### ISSUE TITLE
Fails to build with Boost 1.70.0

### ISSUE THREAD

**Issue by jbeich** [anura-engine/anura#286]
Regressed by boostorg/asio@a72fbb0b867f:
```c++
src/multiplayer_server.cpp:69:48: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
                        socket_ptr socket(new tcp::socket(acceptor_.get_io_service()));
                                                          ~~~~~~~~~ ^
src/tbs_relay_server.cpp:89:61: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
                OutgoingSocketPtr socket(new OutgoingSocketInfo(acceptor_.get_io_service()));
                                                                ~~~~~~~~~ ^
```

**Comment by ghost** [comment]
I think the deprecation traces back to 1.66: https://github.com/boostorg/asio/commit/b60e92b13ef68dfbb9af180d76eae41d22e19356. If so, maybe resolving https://github.com/anura-engine/anura/issues/285 **~~fixes this~~ and then tackling the expectable deprecation messages fixes this**.

**Comment by ghost** [comment]
I think this is going to take a while, because it involves several maintainers and deployments.

For now the best I can advice is to download and build Boost 1.67, and to link and run using a local installation of that Boost version. If you don’t want to fork the engine temporarily.

Thanks for reporting this!
