### PR TITLE
Update Boost requirements.

### PR DESCRIPTION
**Pull request by galegosimpatico**
Update INSTALL. A subsequent commit from me would precise the new
minimum version, I guess unlikely to still be `1.50`.

Related to https://github.com/anura-engine/anura/pull/290.

Related to https://github.com/anura-engine/anura/issues/286.

Proof at
https://github.com/anura-engine/anura/commit/e4a2f2e7b1f99763cef6278bac313450a4fe58c9
(rev e4a2f2e7b1 of 31 Oct 2019).

Proof at
https://github.com/anura-engine/anura/issues/303#issuecomment-667350764.

### CODE REVIEW

**Comment by DDR0** [comment]
Thanks for looking at this. :+1:

**Comment by galegosimpatico** [comment]
D'oh, now reading https://github.com/anura-engine/anura/issues/285 I guess it should be impossible to build using Boost 1.65, I guess it would be safe if we stated `1.66.0 <= boost_iostreams  <= 1.71.0`.

**Comment by galegosimpatico** [comment]
> D'oh, now reading #285 I guess it should be impossible to build using Boost 1.65, I guess it would be safe if we stated `1.66.0 <= boost_iostreams <= 1.71.0`.

No, maybe not, who knows, because of the way https://github.com/anura-engine/anura/pull/284/files is written, considering earlier Boost versions. I wouldn't know for sure until I check exhaustively.

**Comment by galegosimpatico** [comment]
Can't make Boost 1.65.0 work at the mac build.

Output is:
```
dyld: Symbol not found: __ZN5boost11basic_regexIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9do_assignEPKcS7_j
  Referenced from: /Users/$USER/Library/Developer/Xcode/DerivedData/Frogatto-hlcshmgbenlytwcaotmdmpqygrjt/Build/Products/Debug/Frogatto.app/Contents/MacOS/Frogatto
  Expected in: /usr/local/lib/libboost_regex.dylib
 in /Users/$USER/Library/Developer/Xcode/DerivedData/Frogatto-hlcshmgbenlytwcaotmdmpqygrjt/Build/Products/Debug/Frogatto.app/Contents/MacOS/Frogatto
(lldb) _
```

But my word's not final until I can check on GNU/Linux.
