### ISSUE TITLE
Compiler errors with memcpy on non-POD type

### ISSUE THREAD

**Issue by sweetkristas** [anura-engine/anura#270]
```
src/variant.hpp: In member function ‘void variant::swap(variant&)’:
src/variant.hpp:228:36: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class variant’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
    memcpy(&v, this, sizeof(variant));
```

@davewx7 Yeah, just don't do this.

**Comment by sweetkristas** [comment]
You already have a move constructor and move assignment operator, why not use them?
```
            variant tmp = std::move(*this);
            *this = std::move(v);
            v = std::move(tmp);

```

**Comment by davewx7** [comment]
This is a case where using memcpy() is safe and is faster than the other available options.

**Comment by sweetkristas** [comment]
Don't know why you closed this, because just saying something isn't a problem doesn't address the issue that the code won't compile with GCC 8.1.

**Comment by ghost** [comment]
> Don't know why you closed this, because just saying something isn't a problem doesn't address the issue that the code won't compile with GCC 8.1.

Mainstream should be able to compile out of the box already, after 125d9a8f3d404cfef8ff4a1e62b2474899d61fff, or if they don't, please fix.

If you are in `trunk`, you should be fine with that, or I got something wrong.

If you are in a feature branch, or for some reason frozen in a previous version, you don't need to take care of anyone else's builds, do you?

125d9a8f3d404cfef8ff4a1e62b2474899d61fff allows `memcpy` all over the project, not just variants, so you might want to come up with a weaker and more convenient solution.

**Comment by sweetkristas** [comment]
That would be good if 

1. Your commit https://github.com/anura-engine/anura/commit/125d9a8f3d404cfef8ff4a1e62b2474899d61fff actually worked. g++ -dumpversion returns 8 for me, which is g++ (Ubuntu 8.1.0-5ubuntu1~14.04) 8.1.0. So obviously your check in the Makefile is broken.
2. It was good practice to global disable an important warning rather than disabling for a specific case and providing some numbers to back up whether this is in fact faster than other solutions.

**Comment by sweetkristas** [comment]
That

**Comment by davewx7** [comment]
I committed a change to fix this.

**Comment by ghost** [comment]
I made sure I removed my local use of `-Wno-class-memaccess`, and e43ad3a586e533049ce7b108a97ae96cabf02b7a seems to fix the build at the Linux host where I installed GCC 8.

I thought the quick patch 125d9a8f3d404cfef8ff4a1e62b2474899d61fff would be good enough while the compiler didn't like the code, because at the host:

```
$ g++ -dumpversion
6.3.0
$ PATH=/usr/local/gcc/gcc-8.1.0/usr/local/bin/:$PATH g++ -dumpversion
8.1.0
$ _
```

Sorry for the mess! I shall clear my obsolete changes in `Makefile`.
